const Images = {
    HEARTS: {
        KING: "kingofhearts.png",
        QUEEN: "queenofhearts.png",
        JACK: "jackofhearts.png",
        TEN: "tenofhearts.png",
        NINE: "nineofhearts.png",
        EIGHT: "eightofhearts.png",
        SEVEN: "sevenofhearts.png",
        SIX: "sixofhearts.png",
        FIVE: "fiveofhearts.png",
        FOUR: "fourofhearts.png",
        THREE: "threeofhearts.png",
        TWO: "twoofhearts.png",
        ACE: "aceofhearts.png"
    },
    DIAMONDS: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
    CLUBS: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
    SPADES: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
}